[tool.poetry]
name = "foot-lint"
version = "0.1.0"
description = ""
authors = ["iTecAI <matteovh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
rich = "^13.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
